definitions:
  service.AddFriendReply:
    type: object
  service.AddFriendRequest:
    properties:
      friendId:
        type: integer
    type: object
  service.GetCodeReply:
    type: object
  service.GetFriendListReply:
    properties:
      list:
        items:
          $ref: '#/definitions/service.GetFriendListSimple'
        type: array
    type: object
  service.GetFriendListSimple:
    properties:
      avatar:
        type: string
      id:
        type: integer
    type: object
  service.LoginReply:
    properties:
      token:
        description: token
        type: string
    type: object
  service.LoginRequest:
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
    required:
    - email
    - password
    type: object
  service.RegisterReply:
    properties:
      token:
        description: token
        type: string
    type: object
  service.RegisterRequest:
    properties:
      code:
        description: 验证码
        type: string
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      userName:
        description: 用户名
        type: string
    required:
    - code
    - email
    - password
    - userName
    type: object
info:
  contact: {}
paths:
  /add/friend:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 添加好友
        in: body
        name: friend
        required: true
        schema:
          $ref: '#/definitions/service.AddFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AddFriendReply'
      summary: 添加好友
      tags:
      - 好友
  /get/friend:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: friendId
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AddFriendReply'
      summary: 好友信息
      tags:
      - 好友
  /get/friend/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GetFriendListReply'
      summary: 好友列表
      tags:
      - 好友
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登录
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.LoginReply'
      summary: 用户登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户注册
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.RegisterReply'
      summary: 用户注册
      tags:
      - 用户
  /user/register/code:
    get:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GetCodeReply'
      summary: 用户注册获取验证码
      tags:
      - 用户
swagger: "2.0"
